# Generated by Django 4.2.6 on 2024-07-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_index=True, max_length=250)),
                ('lastname', models.CharField(db_index=True, max_length=250, null=True)),
                ('email', models.EmailField(db_index=True, max_length=250, unique=True)),
                ('age', models.IntegerField(db_index=True)),
                ('gender', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
    ]
